apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vehd98i18-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-09998c0067.4lr8.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:45739ed52967c24602dde817413c11daed59288b@sha256:b2420fea78d762604bd006f49ab93c06bd970c28c66d68487fe55a4476c660ff
          name: container-image
